env:
  browser: false
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
globals:
  assert: writeable
  artifacts: writeable
  web3: writeable
  it: writeable
  contract: writeable
  context: writeable
  describe: writeable
  before: writeable
  beforeEach: writeable
  after: writeable
  afterEach: writeable
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console: 0